export default {
  service: `Cet accord est un contrat entre vous et nous concernant les services de ce site Web et d'autres questions connexes. Après avoir cliqué sur "J'ai lu et j'accepte", cet accord constitue un document juridique contraignant pour les deux parties. Avant d'utiliser les services de ce site Web, veuillez lire attentivement cet accord. Si vous n'êtes pas d'accord avec cet accord ou l'un de ses contenus, vous devez cesser immédiatement d'utiliser les services de ce site Web. Si vous utilisez les services de ce site Web, votre comportement d'utilisation sera considéré comme une acceptation de l'intégralité du contenu de cet accord.
Dans le même temps, nous vous rappelons de lire attentivement notre "Politique de confidentialité"
1. Confirmation des conditions d'utilisation
1. Le contenu de cet accord comprend le texte de l'accord et toutes sortes de règles qui ont été publiées ou pourraient être publiées à l'avenir sur ce site Web. Toutes les règles font partie intégrante de cet accord et ont le même effet juridique que le texte de l'accord. Sauf indication contraire expresse, tous les services fournis par nous et nos sociétés affiliées sont régis par le présent Accord. Vous confirmez que les termes de cet accord sont des contrats qui traitent des droits et obligations des deux parties et sont toujours valides, sauf disposition contraire imposée par la loi ou autrement spécialement convenue par les deux parties.
2. Si vous cliquez pour accepter cet accord, vous êtes réputé avoir confirmé que vous disposez des droits et des capacités comportementales correspondants pour profiter des services de ce site Web, passer des commandes et des achats, et être en mesure d'assumer de manière indépendante des responsabilités légales.
3. Si vous avez moins de 16 ans, il est recommandé de demander à votre tuteur de lire attentivement cet accord et d'utiliser les services de ce site Web ou de fournir des informations à ce site Web avec le consentement de votre tuteur. Si vous accomplissez un acte civil incompatible avec votre capacité civile sans le consentement de votre tuteur, vous et votre tuteur supporterez toutes les conséquences juridiques qui en découlent conformément à la loi.
4. Nous nous réservons le droit de refuser le service, de fermer des comptes d'utilisateurs, d'effacer ou de modifier du contenu, d'annuler des commandes, etc. à notre seule discrétion dans la mesure permise par la loi britannique en vigueur.
2. Enregistrement et utilisation du compte
1. Vous devez fournir de bonne foi des informations d'inscription vraies, exactes, complètes, légales et valides sur ce site Web. Si vos informations d'enregistrement changent, vous devez les mettre à jour à temps. Si les informations d'inscription que vous fournissez sont illégales, fausses, inexactes et incomplètes, vous assumerez les responsabilités correspondantes et les conséquences qui en découlent, et nous nous réservons le droit de mettre fin à votre utilisation des services de ce site Web.
2. Une fois votre inscription réussie, les informations de compte telles que le nom d'utilisateur et le mot de passe seront générées et vous pourrez modifier votre mot de passe conformément aux réglementations de ce site Web. Vous devez conserver et utiliser votre nom d'utilisateur et votre mot de passe avec soin et raisonnablement, et accepter et vous engager à être responsable de toutes les activités qui se produisent sous votre compte. Vous ne devez pas transférer ou autoriser d'autres personnes à utiliser votre compte (y compris votre nom d'utilisateur et votre mot de passe) sur ce site Web sous quelque forme que ce soit sans autorisation. Si vous constatez que vos informations personnelles sont divulguées, en particulier les informations de votre compte (telles que le nom d'utilisateur et le mot de passe) sont divulguées ou s'il y a une faille de sécurité, veuillez nous en informer immédiatement afin que nous puissions prendre les mesures correspondantes, et vous devriez prendre l'initiative de signaler le cas à l'autorité judiciaire si nécessaire.
3. Vous acceptez que nous ayons le droit de vous envoyer, ainsi qu'à votre destinataire confirmé, des informations sur les commandes, des activités promotionnelles et d'autres informations par courrier, SMS, appel téléphonique, etc. Si nous vous envoyons des avis ou des messages sous forme électronique, vous serez réputé les avoir reçus.
3. Spécifications d'utilisation du service
1. Cet accord est formulé conformément aux lois, réglementations et règles applicables, et vous vous engagez à respecter strictement les obligations suivantes :
(1) La transmission d'informations sur les données doit être conforme aux lois et réglementations en vigueur.
(2) N'utilisez pas ce site Web pour vous livrer au blanchiment d'argent, au vol de secrets commerciaux, au vol d'informations personnelles et à d'autres activités illégales et criminelles.
(3) Il ne doit pas interférer avec le fonctionnement normal de ce site Web, et ne doit pas envahir ce site Web et le système d'information informatique national.
(4) N'incitez pas les autres à se livrer à des actes interdits par cet article.
(5) N'utilisez pas le compte enregistré sur ce site Web pour des activités commerciales à but lucratif.
2. Nous avons le droit de supprimer toutes sortes d'informations sur ce site Web qui ne sont pas conformes aux lois, réglementations et politiques, violent l'ordre public et les bonnes mœurs, sont fausses et ont expiré sans autre préavis. Si vous violez les dispositions de cet accord, ce site Web a le droit de porter un jugement indépendant et de prendre des mesures telles que la suspension ou la fermeture de votre compte. Vous êtes légalement responsable de ce que vous dites et faites sur ce site.
4. Conditions de propriété et droits de propriété intellectuelle
1. Vous acceptez et comprenez pleinement les termes de cet accord, et vous vous engagez à ne pas publier les informations publiées sur ce site Web sous quelque forme que ce soit ou à autoriser d'autres sujets à les utiliser de quelque manière que ce soit (y compris, mais sans s'y limiter, l'utilisation sur divers sites Web et médias) .
2. Nous sommes les créateurs de ce site Web et détenons les droits d'auteur et autres droits légaux sur le contenu et les ressources de ce site Web. Ils sont protégés par la loi et ont le droit de revoir cet accord et le contenu de ce site Web de temps à autre conformément aux lois, réglementations, changements de politique et besoins commerciaux réels. Apporter des modifications et des mises à jour sur ce site Web sans préavis aux utilisateurs.
3. Sauf obligation légale contraire, sans l'autorisation écrite expresse de ce site Web, aucune unité ou personne ne peut copier, reproduire, citer, lier, saisir ou autrement utiliser ce site Web, en tout ou en partie, de quelque manière que ce soit. Le contenu de l'information du site Web, sinon, nous avons le droit de poursuivre sa responsabilité légale.
V. Clause de non-responsabilité
1. Sauf indication contraire expresse par écrit, ce site Web et toutes les informations, contenus, matériaux, produits (y compris les logiciels) et services contenus ou autrement mis à votre disposition via ce site Web sont fournis "tels quels". et fournis sur une base "selon disponibilité".
2. Sauf indication contraire expresse par écrit, nous ne faisons aucune représentation ou garantie d'aucune sorte, expresse ou implicite, concernant le fonctionnement de ce site Web et les informations, le contenu, les matériaux, les produits (y compris les logiciels) ou les services contenus sur ce site Web (à moins que autrement prévu par la loi britannique).
3. Nous ne garantissons pas que toutes les informations, contenus, matériels, produits (y compris les logiciels) et services contenus ou autrement mis à votre disposition via ce site Web, ses serveurs ou e-mails, les messages envoyés à partir de ce site Web sont exempts de virus ou d'autres éléments nuisibles. Ingrédients.
4. Si le système de vente de ce site Web tombe en panne ou ne peut pas être utilisé normalement en raison d'un cas de force majeure ou d'autres raisons indépendantes de la volonté de ce site Web, la transaction en ligne ne peut pas être effectuée ou les informations et enregistrements pertinents sont perdus, nous ferons de notre mieux pour aider à faire face aux conséquences, mais nous ne le ferons pas. assumer toute responsabilité en matière d'indemnisation.
6. Modification de l'accord
1. Selon les modifications des lois et réglementations applicables et les besoins des opérations du site Web, nous avons le droit de réviser les termes de cet accord et d'autres politiques et annonces du site Web de temps à autre. Une fois le contenu révisé publié sur ce site Web, il entrera en vigueur et remplacera le contenu original. Les utilisateurs doivent vérifier le dernier accord à tout moment.
2. L'utilisateur est tenu de prêter attention et de lire à tout moment la dernière version de l'accord et de l'annonce du site Web. Si vous n'êtes pas d'accord avec le contenu mis à jour, vous devez immédiatement cesser d'accepter les services fournis par ce site Web conformément à cet accord ; si vous continuez à utiliser les services fournis par ce site Web, vous êtes réputé accepter l'accord mis à jour.
3. Nous vous recommandons de lire cet accord et l'annonce de ce site Web avant d'utiliser ce site Web. Si une disposition du présent Accord est réputée nulle, nulle ou inapplicable pour quelque raison que ce soit, cette disposition sera réputée divisible et n'affectera pas la validité et l'applicabilité des dispositions restantes.
7. Autre
1. Nous respectons les droits légaux des utilisateurs et des consommateurs. Cet accord et diverses règles, déclarations et autres contenus publiés sur ce site Web ont pour but de fournir des services meilleurs et plus pratiques aux utilisateurs et aux consommateurs. Ce site Web accueille les commentaires et suggestions des utilisateurs et de tous les horizons. Nous accepterons et réviserons humblement cet accord et diverses règles sur ce site Web en temps voulu.
2. Lorsque vous cochez l'option "Accepter" lors de l'inscription, il est considéré que vous comprenez parfaitement et acceptez d'être lié par cet accord.
3. Veuillez lire les clauses marquées en gras, en gras et soulignées dans le contenu de cet accord.
4. Dans la mesure maximale permise par la loi, nous avons le droit d'interpréter cet accord et le contenu de ce site Web.
`,
privacy:`Ce logiciel respecte et protège la vie privée de tous les utilisateurs qui utilisent le service. Afin de vous fournir des services plus précis et personnalisés, ce logiciel utilisera et divulguera vos informations personnelles conformément aux dispositions de la présente politique de confidentialité. Cependant, ce logiciel traitera ces informations avec un degré élevé de diligence et de prudence. Sauf disposition contraire dans la présente politique de confidentialité, ce logiciel ne divulguera ni ne fournira ces informations à des tiers sans votre autorisation préalable. Ce logiciel mettra à jour cette politique de confidentialité de temps à autre. Lorsque vous acceptez l'accord d'utilisation du service logiciel, vous êtes réputé avoir accepté l'intégralité du contenu de cette politique de confidentialité. Cette politique de confidentialité fait partie intégrante de cet accord d'utilisation du service logiciel.

1. Champ d'application

a) Lorsque vous utilisez les services du réseau logiciel, le logiciel reçoit et enregistre automatiquement les informations sur votre téléphone mobile, y compris, mais sans s'y limiter, vos données de santé, la langue utilisée, la date et l'heure d'accès, les informations sur les fonctionnalités logicielles et matérielles et vos besoins. Page Web enregistrements et autres données ;

2. Utilisation des informations

a) Après avoir obtenu vos données, le logiciel les téléchargera sur le serveur pour générer vos données de classement afin que vous puissiez mieux utiliser le service.

3. Divulgation d'informations

a) Ce logiciel ne divulguera pas vos informations à des tiers non fiables.

b) Conformément aux dispositions pertinentes de la loi ou aux exigences des institutions administratives ou judiciaires, divulguer à des tiers ou à des institutions administratives ou judiciaires ;

4. Stockage et échange d'informations

Les informations et matériels vous concernant collectés par ce logiciel seront enregistrés sur les serveurs de ce logiciel et/ou de ses filiales, et ces informations et matériels peuvent être transmis dans votre pays, région ou en dehors de l'endroit où le logiciel collecte des informations et matériels et in Consulté, stocké et affiché à l'étranger.

5. Sécurité des informations

a) Lorsque vous utilisez les services réseau de ce logiciel pour effectuer des transactions en ligne, vous divulguerez inévitablement vos informations personnelles, telles que vos coordonnées ou votre adresse postale, à la contrepartie ou à la contrepartie potentielle. Veuillez protéger correctement vos informations personnelles et ne les fournissez à d'autres que lorsque cela est nécessaire. Si vous constatez que vos informations personnelles sont divulguées, veuillez contacter immédiatement le service client du logiciel afin que le logiciel puisse prendre les mesures correspondantes.
`
};
