export default {
  service: `Questo accordo è un contratto tra te e noi per quanto riguarda i servizi di questo sito Web e altre questioni correlate. Dopo aver fatto clic su "Ho letto e accetto", questo accordo costituisce un documento legale vincolante per entrambe le parti. Prima di utilizzare i servizi di questo sito Web, leggere attentamente il presente contratto. Se non sei d'accordo con questo accordo o uno qualsiasi dei suoi contenuti, dovresti interrompere immediatamente l'utilizzo dei servizi di questo sito web. Se utilizzi i servizi di questo sito Web, il tuo comportamento di utilizzo sarà considerato come un'accettazione dell'intero contenuto del presente accordo.
Allo stesso tempo, ti ricordiamo di leggere attentamente la nostra "Privacy Policy".
1. Conferma dei Termini di servizio
1. Il contenuto del presente accordo include il testo del contratto e tutti i tipi di regole che sono state pubblicate o potrebbero essere pubblicate in futuro su questo sito web. Tutte le regole sono parte integrante del presente accordo e hanno lo stesso effetto giuridico del testo dell'accordo. Salvo espressa indicazione contraria, tutti i servizi forniti da noi e dai nostri affiliati sono regolati dal presente Accordo. Confermi che i termini del presente accordo sono contratti che trattano i diritti e gli obblighi di entrambe le parti e sono sempre validi, salvo diversa obbligo di legge o altrimenti espressamente concordato da entrambe le parti.
2. Se fai clic per accettare il presente accordo, si ritiene che tu abbia confermato di avere i diritti e le capacità comportamentali corrispondenti per usufruire dei servizi di questo sito Web, effettuare ordini e acquisti e poter assumere autonomamente responsabilità legali.
3. Se hai meno di 16 anni, ti consigliamo di chiedere al tuo tutore di leggere attentamente questo accordo e di utilizzare i servizi di questo sito Web o di fornire informazioni a questo sito Web con il consenso del tuo tutore. Se compi un atto civile che non è coerente con la tua capacità civile senza il consenso del tuo tutore, tu e il tuo tutore sopporterai tutte le conseguenze legali che ne derivano in conformità con la legge.
4. Ci riserviamo il diritto di rifiutare il servizio, chiudere gli account utente, cancellare o modificare il contenuto, annullare gli ordini, ecc. a nostra esclusiva discrezione nella misura consentita dall'attuale legge britannica.
2. Registrazione e utilizzo dell'account
1. È necessario fornire informazioni di registrazione veritiere, accurate, complete, legali e valide a questo sito Web in buona fede. Se le tue informazioni di registrazione cambiano, dovresti aggiornarle in tempo. Se le informazioni di registrazione fornite sono illegali, false, inesatte e incomplete, l'utente si assume le corrispondenti responsabilità e conseguenze che ne derivano e ci riserviamo il diritto di interrompere l'utilizzo dei servizi di questo sito Web.
2. Dopo esserti registrato con successo, verranno generate informazioni sull'account come nome utente e password e potrai modificare la tua password in base alle normative di questo sito Web. Conserverai e utilizzerai il tuo nome utente e password in modo accurato e ragionevole e accetti e ti impegni a essere responsabile di tutte le attività che si verificano sotto il tuo account. Non devi trasferire o autorizzare altri a utilizzare il tuo account (inclusi nome utente e password) su questo sito Web in qualsiasi forma senza autorizzazione. Se scopri che le tue informazioni personali sono trapelate, in particolare le informazioni del tuo account (come nome utente e password) sono trapelate o c'è una violazione della sicurezza, ti preghiamo di informarci immediatamente in modo che possiamo prendere le misure corrispondenti e dovresti prendere l'iniziativa per segnalare il caso all'autorità giudiziaria, se necessario.
3. Accetti che abbiamo il diritto di inviare informazioni sull'ordine, attività promozionali e altre informazioni a te e al tuo destinatario confermato tramite posta, SMS, telefonata, ecc. Se ti inviamo avvisi o messaggi in formato elettronico, sarai ritenuto di averli ricevuti.
3. Specifiche di utilizzo del servizio
1. Il presente accordo è formulato in conformità con le leggi, i regolamenti e le norme pertinenti e l'utente accetta di attenersi rigorosamente ai seguenti obblighi:
(1) La trasmissione di informazioni sui dati deve essere conforme alle leggi e ai regolamenti pertinenti.
(2) Non utilizzare questo sito Web per riciclare denaro, rubare segreti aziendali, rubare informazioni personali e altre attività illegali e criminali.
(3) Non deve interferire con il normale funzionamento di questo sito Web e non invadere questo sito Web e il sistema informatico nazionale.
(4) Non istigare altri a compiere atti proibiti dal presente articolo.
(5) Non utilizzare l'account registrato su questo sito Web per attività commerciali a scopo di lucro.
2. Abbiamo il diritto di eliminare tutti i tipi di contenuti informativi su questo sito Web che non sono conformi a leggi, regolamenti e politiche, violano l'ordine pubblico e la buona morale, sono falsi e sono scaduti senza ulteriore avviso. In caso di violazione delle disposizioni del presente accordo, questo sito Web ha il diritto di esprimere un giudizio indipendente e adottare misure come la sospensione o la chiusura dell'account. Sei legalmente responsabile di ciò che dici e fai su questo sito web.
4. Termini di proprietà e diritti di proprietà intellettuale
1. Accetti e comprendi pienamente i termini del presente accordo e prometti di non pubblicare le informazioni pubblicate su questo sito Web in alcuna forma o di autorizzare altri soggetti a utilizzarle in alcun modo (incluso, a titolo esemplificativo, l'uso su vari siti Web e media) .
2. Siamo i creatori di questo sito Web e deteniamo il copyright e altri diritti legali del contenuto e delle risorse di questo sito Web. Sono protetti dalla legge e hanno il diritto di rivedere il presente accordo e il contenuto di questo sito Web di volta in volta in conformità con le leggi, i regolamenti, le modifiche alle politiche e le effettive esigenze aziendali. Apportare modifiche e aggiornamenti su questo sito Web senza preavviso agli utenti.
3. Salvo quanto diversamente previsto dalla legge, senza l'espresso consenso scritto di questo sito Web, nessuna unità o individuo può illegalmente copiare, riprodurre, citare, collegare, afferrare o altrimenti utilizzare questo sito Web in tutto o in parte in qualsiasi modo. Il contenuto informativo del sito web, in caso contrario, abbiamo il diritto di perseguire la sua responsabilità legale.
V. Disclaimer
1. Salvo diversa espressa indicazione scritta, questo sito Web e tutte le informazioni, i contenuti, i materiali, i prodotti (incluso il software) e i servizi contenuti o altrimenti resi disponibili all'utente tramite questo sito Web sono forniti "così come sono". e forniti "secondo disponibilità".
2. Salvo diversa espressa indicazione scritta, non rilasciamo dichiarazioni o garanzie di alcun tipo, esplicite o implicite, in merito al funzionamento di questo sito Web e alle informazioni, contenuti, materiali, prodotti (incluso il software) o servizi contenuti in questo sito Web (a meno che altrimenti previsto dalla legge britannica).
3. Non garantiamo che tutte le informazioni, i contenuti, i materiali, i prodotti (incluso il software) e i servizi contenuti o altrimenti resi disponibili all'utente tramite questo sito Web, i suoi server o e-mail, i messaggi inviati da questo sito Web sono privi di virus o altri dannosi ingredienti.
4. Se il sistema di vendita di questo sito Web si arresta in modo anomalo o non può essere utilizzato normalmente a causa di forza maggiore o altri motivi al di fuori del controllo di questo sito Web, la transazione online non può essere completata o le informazioni e i record pertinenti vengono persi, faremo del nostro meglio per assisteremo nell'affrontare le conseguenze, ma non lo faremo. assumersi ogni responsabilità per risarcimenti.
6. Modifica dell'accordo
1. In base alle modifiche delle leggi e dei regolamenti pertinenti e alle esigenze delle operazioni del sito Web, abbiamo il diritto di rivedere i termini del presente accordo e altre politiche e annunci del sito Web di volta in volta. Una volta che il contenuto rivisto sarà pubblicato su questo sito Web, avrà effetto e sostituirà il contenuto originale. Gli utenti dovrebbero controllare l'ultimo accordo in qualsiasi momento.
2. L'utente è obbligato a prestare attenzione e leggere in qualsiasi momento l'ultima versione del contratto e l'annuncio del sito web. Se non sei d'accordo con il contenuto aggiornato, dovresti interrompere immediatamente l'accettazione dei servizi forniti da questo sito Web in conformità con il presente accordo; se continui a utilizzare i servizi forniti da questo sito web, si considera che accetti il ​​contratto aggiornato.
3. Si consiglia di leggere il presente contratto e l'annuncio di questo sito Web prima di utilizzare questo sito Web. Se una qualsiasi disposizione del presente Accordo è considerata nulla, nulla o inapplicabile per qualsiasi motivo, tale disposizione sarà considerata separabile e non pregiudicherà la validità e l'applicabilità delle restanti disposizioni.
7. Altro
1. Rispettiamo i diritti legali degli utenti e dei consumatori. Il presente accordo e varie regole, dichiarazioni e altri contenuti pubblicati su questo sito Web hanno lo scopo di fornire servizi migliori e più convenienti per utenti e consumatori. Questo sito Web accoglie commenti e suggerimenti dagli utenti e da tutti i ceti sociali. Accetteremo umilmente e rivedremo questo accordo e varie regole su questo sito web a tempo debito.
2. Quando si seleziona l'opzione "Accetto" durante la registrazione, si considera che l'utente comprenda pienamente e accetti di essere vincolato da questo accordo.
3. Si prega di leggere le clausole contrassegnate in grassetto, grassetto e sottolineate nel contenuto del presente accordo.
4. Nella misura massima consentita dalla legge, abbiamo il diritto di interpretare il presente accordo e i contenuti di questo sito web.
`,
privacy:`Questo software rispetta e protegge la privacy personale di tutti gli utenti che utilizzano il servizio. Al fine di fornirti servizi più accurati e personalizzati, questo software utilizzerà e divulgherà le tue informazioni personali in conformità con le disposizioni della presente Informativa sulla privacy. Tuttavia, questo software tratterà queste informazioni con un alto grado di diligenza e prudenza. Salvo quanto diversamente previsto nella presente Informativa sulla privacy, questo software non divulgherà o fornirà queste informazioni a terzi senza il tuo previo consenso. Questo software aggiornerà questa politica sulla privacy di volta in volta. Quando accetti l'accordo sull'uso del servizio software, si considera che tu abbia accettato l'intero contenuto della presente informativa sulla privacy. La presente informativa sulla privacy è parte integrante del presente contratto di utilizzo del servizio software.

1. Ambito di applicazione

a) Quando utilizzi i servizi di rete del software, il software riceve e registra automaticamente le informazioni sul tuo telefono cellulare, inclusi, a titolo esemplificativo ma non esaustivo, i tuoi dati sanitari, la lingua utilizzata, la data e l'ora di accesso, le informazioni sulle funzionalità software e hardware e le tue esigenze Pagina Web record e altri dati;

2. Uso delle informazioni

a) Dopo aver ottenuto i tuoi dati, il software li caricherà sul server per generare i tuoi dati di ranking in modo da poter utilizzare al meglio il servizio.

3. Divulgazione delle informazioni

a) Questo software non divulgherà le tue informazioni a terze parti non affidabili.

b) la comunicazione a terzi oa istituzioni amministrative o giudiziarie, conformemente a disposizioni di legge in materia, oa disposizioni di istituzioni amministrative o giudiziarie;

4. Archiviazione e scambio di informazioni

Le informazioni e i materiali su di te raccolti da questo software verranno salvati sui server di questo software e/o delle sue affiliate e tali informazioni e materiali possono essere trasmessi al tuo paese, regione o al di fuori del luogo in cui il software raccoglie informazioni e materiali e in Accessibile, archiviato e visualizzato all'estero.

5. Sicurezza delle informazioni

a) Quando utilizzi i servizi di rete di questo software per condurre transazioni online, rivelerai inevitabilmente le tue informazioni personali, come le informazioni di contatto o l'indirizzo postale, alla controparte o alla potenziale controparte. Si prega di proteggere adeguatamente le informazioni personali e di fornirle ad altri solo quando necessario. Se scopri che le tue informazioni personali sono trapelate, contatta immediatamente il servizio clienti del software in modo che il software possa adottare le misure corrispondenti
`
};
