export default {
  service: `Deze overeenkomst is een contract tussen u en ons met betrekking tot de diensten van deze website en andere gerelateerde zaken. Nadat u op "Ik heb gelezen en akkoord" heeft geklikt, vormt deze overeenkomst een bindend juridisch document voor beide partijen. Lees deze overeenkomst aandachtig door voordat u gebruik maakt van de diensten van deze website. Als u niet akkoord gaat met deze overeenkomst of de inhoud ervan, moet u onmiddellijk stoppen met het gebruik van de diensten van deze website. Als u gebruik maakt van de diensten van deze website, wordt uw gebruiksgedrag beschouwd als een aanvaarding van de volledige inhoud van deze overeenkomst.
Tegelijkertijd herinneren we u eraan om ons "Privacybeleid" aandachtig te lezen
1. Bevestiging van de servicevoorwaarden
1. De inhoud van deze overeenkomst omvat de tekst van de overeenkomst en allerlei regels die op deze website zijn of in de toekomst gepubliceerd zijn. Alle regels maken integraal deel uit van deze overeenkomst en hebben dezelfde rechtskracht als de tekst van de overeenkomst. Tenzij uitdrukkelijk anders vermeld, vallen alle diensten die door ons en onze gelieerde ondernemingen worden geleverd, onder deze Overeenkomst. U bevestigt dat de voorwaarden van deze overeenkomst contracten zijn die handelen over de rechten en plichten van beide partijen en altijd geldig zijn, tenzij anders verplicht door de wet of anderszins speciaal door beide partijen overeengekomen.
2. Als u klikt om akkoord te gaan met deze overeenkomst, wordt u geacht te hebben bevestigd dat u over de overeenkomstige rechten en gedragsvaardigheden beschikt om van de diensten van deze website te genieten, bestellingen en aankopen te plaatsen en in staat te zijn om onafhankelijk wettelijke verantwoordelijkheden op zich te nemen.
3. Als u jonger bent dan 16 jaar, is het raadzaam uw voogd te vragen deze overeenkomst aandachtig te lezen, en met toestemming van uw voogd gebruik te maken van de diensten van deze website of informatie aan deze website te verstrekken. Als u zonder toestemming van uw voogd een burgerlijke handeling verricht die in strijd is met uw burgerlijke hoedanigheid, dragen u en uw voogd alle daaruit voortvloeiende rechtsgevolgen in overeenstemming met de wet.
4. We behouden ons het recht voor om naar eigen goeddunken service te weigeren, gebruikersaccounts te sluiten, inhoud te wissen of te bewerken, bestellingen te annuleren, enz. voor zover toegestaan ​​door de huidige Britse wetgeving.
2. Accountregistratie en gebruik
1. U dient te goeder trouw waarheidsgetrouwe, nauwkeurige, volledige, wettelijke en geldige registratie-informatie aan deze website te verstrekken. Als uw registratiegegevens veranderen, moet u deze op tijd bijwerken. Als de registratie-informatie die u verstrekt onwettig, onwaar, onnauwkeurig en onvolledig is, draagt ​​u de overeenkomstige verantwoordelijkheden en gevolgen die daaruit voortvloeien, en behouden wij ons het recht voor om uw gebruik van de diensten van deze website te beëindigen.
2. Nadat u zich succesvol heeft geregistreerd, wordt accountinformatie zoals gebruikersnaam en wachtwoord gegenereerd en kunt u uw wachtwoord wijzigen volgens de voorschriften van deze website. U dient uw gebruikersnaam en wachtwoord zorgvuldig en redelijk te bewaren en te gebruiken, en stemt ermee in en verbindt zich ertoe verantwoordelijk te zijn voor alle activiteiten die plaatsvinden onder uw account. U mag uw account (inclusief gebruikersnaam en wachtwoord) op deze website in geen enkele vorm zonder toestemming overdragen of aan anderen machtigen. Als u merkt dat uw persoonlijke gegevens zijn gelekt, met name uw accountgegevens (zoals gebruikersnaam en wachtwoord) of als er een inbreuk op de beveiliging is, neem dan onmiddellijk contact met ons op zodat we overeenkomstige maatregelen kunnen nemen, en u dient het initiatief te nemen om indien nodig de zaak melden bij de gerechtelijke autoriteit.
3. U stemt ermee in dat wij het recht hebben om u en uw bevestigde geadresseerde het recht te geven om informatie over bestellingen, promotionele activiteiten en andere informatie per post, sms, telefoontje, enz. te sturen. Als wij u kennisgevingen of berichten in elektronische vorm sturen, wordt u geacht deze te hebben ontvangen.
3. Specificaties voor servicegebruik
1. Deze overeenkomst is opgesteld in overeenstemming met de relevante wet-, regelgeving en regels, en u stemt ermee in zich strikt te houden aan de volgende verplichtingen:
(1) De overdracht van gegevensinformatie moet voldoen aan de relevante wet- en regelgeving.
(2) Gebruik deze website niet voor het witwassen van geld, het stelen van bedrijfsgeheimen, het stelen van persoonlijke informatie en andere illegale en criminele activiteiten.
(3) Het zal de normale werking van deze website niet verstoren en zal deze website en het nationale computerinformatiesysteem niet binnendringen.
(4) Zet ​​anderen niet aan tot handelingen die door dit artikel worden verboden.
(5) Gebruik het account dat op deze website is geregistreerd niet voor winstgevende zakelijke activiteiten.
2. We hebben het recht om alle soorten informatie-inhoud op deze website te verwijderen die niet in overeenstemming is met wetten, voorschriften en beleid, de openbare orde en goede zeden schenden, onwaar zijn en zijn verlopen zonder verdere kennisgeving aan u. Als u de bepalingen van deze overeenkomst schendt, heeft deze website het recht om een ​​onafhankelijk oordeel te vellen en maatregelen te nemen zoals het opschorten of sluiten van uw account. U bent wettelijk verantwoordelijk voor wat u zegt en doet op deze website.
4. Eigendomsrechten en intellectuele eigendomsrechten
1. U gaat akkoord met en begrijpt de voorwaarden van deze overeenkomst volledig, en belooft de informatie die op deze website is gepubliceerd in welke vorm dan ook niet te publiceren of andere personen toestemming te geven deze op enigerlei wijze te gebruiken (inclusief maar niet beperkt tot gebruik op verschillende websites en media) .
2. Wij zijn de makers van deze website en hebben het auteursrecht en andere wettelijke rechten op de inhoud en bronnen van deze website. Ze zijn wettelijk beschermd en hebben het recht om deze overeenkomst en de inhoud van deze website van tijd tot tijd te herzien in overeenstemming met wetten, voorschriften, beleidswijzigingen en werkelijke zakelijke behoeften. Breng wijzigingen en updates aan op deze website zonder kennisgeving aan gebruikers.
3. Tenzij wettelijk anders verplicht, mag zonder de uitdrukkelijke schriftelijke toestemming van deze website, geen enkele eenheid of persoon deze website op enigerlei wijze geheel of gedeeltelijk illegaal kopiëren, reproduceren, citeren, linken, grijpen of anderszins gebruiken. De informatieve inhoud van de website, anders hebben wij het recht om haar wettelijke verantwoordelijkheid na te streven.
V. Disclaimer
1. Tenzij uitdrukkelijk schriftelijk anders vermeld, worden deze website en alle informatie, inhoud, materialen, producten (inclusief software) en diensten die zijn opgenomen in of anderszins aan u beschikbaar worden gesteld via deze website, geleverd op een "as is"-basis. en verstrekt op een "zoals beschikbaar"-basis.
2. Tenzij uitdrukkelijk schriftelijk anders vermeld, geven wij geen verklaringen of garanties van welke aard dan ook, expliciet of impliciet, met betrekking tot de werking van deze website en de informatie, inhoud, materialen, producten (inclusief software) of diensten op deze website (tenzij anders bepaald door de Britse wetgeving).
3. We garanderen niet dat alle informatie, inhoud, materialen, producten (inclusief software) en diensten die zijn opgenomen in of anderszins aan u beschikbaar worden gesteld via deze website, de servers of e-mails, berichten die vanaf deze website worden verzonden, vrij zijn van virussen of andere schadelijke ingrediënten.
4. Als het verkoopsysteem van deze website crasht of niet normaal kan worden gebruikt vanwege overmacht of andere redenen buiten de controle van deze website, de online transactie niet kan worden voltooid of de relevante informatie en gegevens verloren gaan, zullen we ons best doen om helpen bij het omgaan met de nasleep, maar dat doen we niet. enige aansprakelijkheid voor schadevergoeding aanvaarden.
6. Overeenkomst wijzigen
1. In overeenstemming met wijzigingen in relevante wet- en regelgeving en de behoeften van websiteactiviteiten, hebben we het recht om de voorwaarden van deze overeenkomst en ander websitebeleid en aankondigingen van tijd tot tijd te herzien. Zodra de herziene inhoud op deze website is gepubliceerd, wordt deze van kracht en vervangt deze de oorspronkelijke inhoud. Gebruikers moeten op elk moment de meest recente overeenkomst controleren.
2. De gebruiker is verplicht om te allen tijde kennis te nemen van de laatste versie van de overeenkomst en de aankondiging van de website. Als u het niet eens bent met de bijgewerkte inhoud, moet u onmiddellijk stoppen met het accepteren van de diensten die door deze website worden geleverd in overeenstemming met deze overeenkomst; als u doorgaat met het gebruiken van de diensten van deze website, wordt u geacht akkoord te gaan met de bijgewerkte overeenkomst.
3. Wij raden u aan deze overeenkomst en de aankondiging van deze website te lezen voordat u deze website gebruikt. Als een bepaling van deze Overeenkomst om welke reden dan ook nietig, nietig of niet-afdwingbaar wordt geacht, wordt die bepaling als scheidbaar beschouwd en heeft deze geen invloed op de geldigheid en afdwingbaarheid van de overige bepalingen.
7. Overig
1. Wij respecteren de wettelijke rechten van gebruikers en consumenten. Deze overeenkomst en verschillende regels, verklaringen en andere inhoud die op deze website worden gepubliceerd, hebben tot doel om gebruikers en consumenten betere en gemakkelijkere diensten te bieden. Deze website verwelkomt opmerkingen en suggesties van gebruikers en alle lagen van de bevolking. We zullen deze overeenkomst en verschillende regels op deze website te zijner tijd nederig accepteren en herzien.
2. Wanneer u tijdens de registratie de optie "Akkoord" aanvinkt, wordt aangenomen dat u deze overeenkomst volledig begrijpt en ermee instemt gebonden te zijn.
3. Lees de vetgedrukte, vetgedrukte en onderstreepte clausules in de inhoud van deze overeenkomst.
4. Voor zover wettelijk toegestaan, hebben wij het recht om deze overeenkomst en de inhoud van deze website te interpreteren.
`,
privacy:`Deze software respecteert en beschermt de persoonlijke privacy van alle gebruikers die de dienst gebruiken. Om u nauwkeurigere en gepersonaliseerde diensten te kunnen bieden, zal deze software uw persoonlijke gegevens gebruiken en vrijgeven in overeenstemming met de bepalingen van dit privacybeleid. Deze software zal deze informatie echter met een hoge mate van zorgvuldigheid en voorzichtigheid behandelen. Tenzij anders bepaald in dit privacybeleid, zal deze software deze informatie niet openbaar maken of verstrekken aan derden zonder uw voorafgaande toestemming. Deze software zal dit privacybeleid van tijd tot tijd bijwerken. Wanneer u akkoord gaat met de overeenkomst voor het gebruik van softwareservices, wordt u geacht akkoord te gaan met de volledige inhoud van dit privacybeleid. Dit privacybeleid is een integraal onderdeel van deze overeenkomst voor het gebruik van softwareservices.

1. Toepassingsgebied

a) Wanneer u de softwarenetwerkdiensten gebruikt, ontvangt en registreert de software automatisch de informatie op uw mobiele telefoon, inclusief maar niet beperkt tot uw gezondheidsgegevens, gebruikte taal, toegangsdatum en -tijd, software- en hardwarefunctie-informatie en uw behoeften webpagina dossiers en andere gegevens;

2. Gebruik van informatie

a) Na het verkrijgen van uw gegevens, zal de software deze uploaden naar de server om uw rangschikkingsgegevens te genereren, zodat u de service beter kunt gebruiken.

3. Openbaarmaking van informatie

a) Deze software zal uw informatie niet bekendmaken aan niet-vertrouwde derden.

b) in overeenstemming met de relevante bepalingen van de wet, of de vereisten van administratieve of gerechtelijke instellingen, openbaar maken aan derden of administratieve of gerechtelijke instellingen;

4. Opslag en uitwisseling van informatie

De informatie en materialen over u die door deze software worden verzameld, worden opgeslagen op de servers van deze software en/of zijn gelieerde ondernemingen, en deze informatie en materialen kunnen worden verzonden naar uw land, regio of buiten de plaats waar de software informatie en materialen verzamelt en in Betreden, opgeslagen en weergegeven in het buitenland.

5. Informatiebeveiliging

a) Wanneer u de netwerkdiensten van deze software gebruikt om online transacties uit te voeren, maakt u onvermijdelijk uw persoonlijke gegevens, zoals contactgegevens of postadres, bekend aan de tegenpartij of potentiële tegenpartij. Bescherm uw persoonlijke gegevens goed en geef deze alleen aan anderen als dat nodig is. Als u constateert dat uw persoonlijke gegevens zijn gelekt, neem dan onmiddellijk contact op met de klantenservice van de software zodat de software passende maatregelen kan nemen
`
};
