export default {
  cn: {
    100: "系统错误",
    101: "系统错误",
    102: "系统错误",
    103: "系统错误",
    104: "登录失效",
    105: "系统负载过大",
    200: "验证码不正确",
    201: "密码不正确",
    202: "用户已经存在",
    203: "用户名无效",
    204: "邀请码无效",
    205: "账户已停用",
    206: "用户没有权限",
    207: "手机号码无效",
    208: "余额不足",
    209: "余额不足",
    210: "钱包地址已经存在",
    211: "主网无效",
    212: "邮箱无效",
    213: "用户名无效",
    214: "用户不存在",
    215: "原密码无效",
    216: "您已经绑定提现地址了！",
    217: "无法充值，请联系客服!",
    218: "您的账户没有取款权限，请联系客服!",
    300: "房间未找到",
    301: "房间已关闭",
    302: "商品未找到",
    303: "你已经用过这个轮子优惠券了",
    400: "订单已满",
    401: "订单已完成",
    402: "您无法下订单",
    403: "余额不足",
    404: "今日抽奖次数已经用完！",
    405: "您的上一个订单还未完成",
    407: "您的订单已被拒绝",
    409: "此订单已经完成!",
    500: "系统错误",
    600: "用户应在最低价格和最高价格之间取得平衡",
    'LoginFirst':"请先登录 ！",
  },
  en: {
    100: "System error",
    101: "System Not Found",
    102: "System wrong param",
    103: "System Error Validation",
    104: "System token expired",
    105: "System payload too large",
    200: "Incorrect verification code",
    201: "User wrong password",
    202: "User already exist",
    203: "Username Invalid",
    204: "Invalid invite code",
    205: "This account is disabled",
    206: "User no permission",
    207: "Invalid Phone number",
    208: "User don't have balance",
    209: "Insufficient Balance",
    210: "This wallet address already exists",
    211: "Invalid mainnet",
    212: "Invalid Email",
    213: "Invalid Username",
    214: "User doesn't exist",
    215: "Invalid old password",
    216: "You already bind withdraw address!",
    217: "You don't have permission to deposit,please contact customer service",
    218: "You don't have permission to withdraw,please contact customer service",
    300: "Room not found",
    301: "This Room is close",
    302: "Good not found",
    303: "You already used this wheel cupon!",
    400: "Today order limit is full",
    401: "This order already complete",
    402: "You cannot create an order",
    403: "Insufficient balance",
    404: "No spin chance today",
    405: "Your last order didn't finished yet!",
    407: "Your order have been rejected",
    409: "This order already finish !",
    500: "System Error",
    600: "Your balane should betweem minimum price and maximun price",
    'LoginFirst':"Please Login first !",
  },
  es:{
    100: "Error del sistema",
    101: "Sistema no encontrado",
    102: "Parámetro erróneo del sistema",
    103: "Validación de errores del sistema",
    104: "Token del sistema caducado",
    105: "Carga útil del sistema demasiado grande",
    200: "Código de verificación incorrecto",
    201: "Contraseña incorrecta del usuario",
    202: "El usuario ya existe",
    203: "Nombre de usuario no válido",
    204: "Código de invitación no válido",
    205: "Esta cuenta está deshabilitada",
    206: "Usuario sin permiso",
    207: "Número de teléfono no válido",
    208: "Usuario no tiene saldo",
    209: "Saldo insuficiente",
    210: "Esta dirección de billetera ya existe",
    211: "Red principal no válida",
    212: "Correo electrónico no válido",
    213: "Nombre de usuario no válido",
    214: "El usuario no existe",
    215: "Contraseña antigua no válida",
    216: "¡Ya vinculaste retirar dirección!",
    217: "No tiene permiso para depositar, comuníquese con el servicio al cliente",
    218: "No tiene permiso para retirar, comuníquese con el servicio al cliente",
    300: "Habitación no encontrada",
    301: "Esta habitación está cerca",
    302: "Bien no encontrado",
    303: "¡Ya usaste este cupón de rueda!",
    400: "El límite de pedido de hoy está lleno",
    401: "Este pedido ya está completo",
    402: "No se puede crear un pedido",
    403: "Saldo insuficiente",
    404: "No hay posibilidad de giro hoy",
    405: "¡Tu último pedido aún no terminó!",
    407: "Tu pedido ha sido rechazado",
    409: "¡Este pedido ya terminó!",
    500: "Error del sistema",
    600: "Tu balance debe estar entre precio minimo y precio maximo",
    'LoginFirst':"Por favor ingresa primero !",
  },
  it: {
    100: "Errore di sistema",
    101: "Sistema non trovato",
    102: "Parametro errato di sistema",
    103: "Convalida errore di sistema",
    104: "Token di sistema scaduto",
    105: "Carico utile di sistema troppo grande",
    200: "Codice di verifica errato",
    201: "Password utente errata",
    202: "Utente già esistente",
    203: "Nome utente non valido",
    204: "Codice invito non valido",
    205: "Questo account è disabilitato",
    206: "Utente nessun permesso",
    207: "Numero di telefono non valido",
    208: "L'utente non ha saldo",
    209: "Equilibrio insufficiente",
    210: "Questo indirizzo di portafoglio esiste già",
    211: "Mainnet non valida",
    212: "E-mail non valida",
    213: "Nome utente non valido",
    214: "L'utente non esiste",
    215: "Vecchia password non valida",
    216: "Lei già l'indirizzo di ritiro!",
    217: "Non hai il permesso di depositare, contatta il servizio clienti",
    218: "Non sei autorizzato a recedere, contatta il servizio clienti",
    300: "Camera non trovata",
    301: "Questa stanza è vicina",
    302: "Buono non trovato",
    303: "Hai già usato questo cupon a ruota!",
    400: "Oggi il limite dell'ordine è pieno",
    401: "Questo ordine già completato",
    402: "Non puoi creare un ordine",
    403: "Equilibrio insufficiente",
    404: "Nessuna possibilità di rotazione oggi",
    405: "Il tuo ultimo ordine non è ancora terminato!",
    407: "Il tuo ordine è stato rifiutato",
    409: "Questo ordine è già terminato!",
    500: "Errore di sistema",
    600: "Le tue balane dovrebbero essere comprese tra prezzo minimo e prezzo massimo",
    'LoginFirst':"Per favore fai prima il log in !",
  },
  se: {
    100: "Systemfel",
    101: "Systemet hittades inte",
    102: "System fel param",
    103: "Systemfelvalidering",
    104: "Systemtoken har gått ut",
    105: "Systemets nyttolast för stor",
    200: "Felaktig verifieringskod",
    201: "Användare fel lösenord",
    202: "Användaren finns redan",
    203: "Ogiltigt användarnamn",
    204: "Ogiltig inbjudningskod",
    205: "Detta konto är inaktiverat",
    206: "Användare ingen behörighet",
    207: "Ogiltigt telefonnummer",
    208: "Användaren har inte balans",
    209: "Otillräcklig balans",
    210: "Denna plånboksadress finns redan",
    211: "Ogiltigt huvudnät",
    212: "Ogiltig e-post",
    213: "Ogiltigt användarnamn",
    214: "Användaren finns inte",
    215: "Ogiltigt gammalt lösenord",
    216: "Du binder redan ta ut adress!",
    217: "Du har inte behörighet att sätta in, kontakta kundtjänst",
    218: "Du har inte tillåtelse att dra tillbaka, kontakta kundtjänst",
    300: "Rum hittades inte",
    301: "Detta rum är nära",
    302: "Bra inte hittat",
    303: "Du har redan använt den här hjulkupongen!",
    400: "Idag ordergräns är full",
    401: "Denna beställning är redan klar",
    402: "Du kan inte skapa en beställning",
    403: "Otillräcklig balans",
    404: "Ingen snurrchans idag",
    405: "Din senaste beställning är inte klar ännu!",
    407: "Din beställning har avvisats",
    409: "Denna beställning är redan klar!",
    500: "Systemfel",
    600: "Din balane bör ligga mellan minimipris och maxpris",
    'LoginFirst':"Snälla logga in först !",
  },
  gr: {
    100: "Σφάλμα συστήματος",
    101: "Το σύστημα δεν βρέθηκε",
    102: "Λάθος παράμετρος συστήματος",
    103: "Επικύρωση σφάλματος συστήματος",
    104: "Το διακριτικό συστήματος έληξε",
    105: "Πολύ μεγάλο ωφέλιμο φορτίο συστήματος",
    200: "Εσφαλμένος κωδικός επαλήθευσης",
    201: "Λάθος κωδικός πρόσβασης χρήστη",
    202: "Ο χρήστης υπάρχει ήδη",
    203: "Μη έγκυρο όνομα χρήστη",
    204: "Μη έγκυρος κωδικός πρόσκλησης",
    205: "Αυτός ο λογαριασμός είναι απενεργοποιημένος",
    206: "Χρήστη χωρίς άδεια",
    207: "Μη έγκυρος αριθμός τηλεφώνου",
    208: "Ο χρήστης δεν έχει υπόλοιπο",
    209: "Ανεπαρκές υπόλοιπο",
    210: "Αυτή η διεύθυνση πορτοφολιού υπάρχει ήδη",
    211: "Μη έγκυρο κεντρικό δίκτυο",
    212: "Μη έγκυρο email",
    213: "Μη έγκυρο όνομα χρήστη",
    214: "Ο χρήστης δεν υπάρχει",
    215: "Μη έγκυρος παλιός κωδικός πρόσβασης",
    216: "Δεσμεύετε ήδη τη διεύθυνση ανάληψης!",
    217: "Δεν έχετε άδεια κατάθεσης, επικοινωνήστε με την εξυπηρέτηση πελατών",
    218: "Δεν έχετε άδεια υπαναχώρησης, επικοινωνήστε με την εξυπηρέτηση πελατών",
    300: "Το δωμάτιο δεν βρέθηκε",
    301: "Αυτό το δωμάτιο είναι κοντά",
    302: "Καλό δεν βρέθηκε",
    303: "Χρησιμοποιήσατε ήδη αυτό το κουπόνι τροχού!",
    400: "Σήμερα το όριο παραγγελίας είναι πλήρες",
    401: "Αυτή η παραγγελία έχει ήδη ολοκληρωθεί",
    402: "Δεν μπορείτε να δημιουργήσετε μια παραγγελία",
    403: "Ανεπαρκές υπόλοιπο",
    404: "Δεν υπάρχει πιθανότητα περιστροφής σήμερα",
    405: "Η τελευταία σας παραγγελία δεν ολοκληρώθηκε ακόμα!",
    407: "Η παραγγελία σας έχει απορριφθεί",
    409: "Αυτή η παραγγελία έχει ήδη τελειώσει!",
    500: "Σφάλμα συστήματος",
    600: "Το υπόλοιπο σας πρέπει να είναι μεταξύ της ελάχιστης τιμής και της μέγιστης τιμής",
    'LoginFirst':"Παρακαλούμε συνδεθείτε πρώτα !",
  },
  rs: {
    100: "Системска грешка",
    101: "Систем није пронађен",
    102: "Систем је погрешан параметар",
    103: "Провера системске грешке",
    104: "Системски токен је истекао",
    105: "Корисно оптерећење система је превелико",
    200: "Нетачан верификациони код",
    201: "Корисничка погрешна лозинка",
    202: "Корисник већ постоји",
    203: "Корисничко име је неважеће",
    204: "Неважећи код позива",
    205: "Овај налог је онемогућен",
    206: "Корисник нема дозволу",
    207: "Неважећи број телефона",
    208: "Корисник нема баланс",
    209: "Недовољна равнотежа",
    210: "Ова адреса новчаника већ постоји",
    211: "Неважећа главна мрежа",
    212: "Неважећа е-пошта",
    213: "Неважеће корисничко име",
    214: "Корисник не постоји",
    215: "Неважећа стара лозинка",
    216: "Већ сте везали адресу за повлачење!",
    217: "Немате дозволу за депозит, молимо контактирајте корисничку подршку",
    218: "Немате дозволу за повлачење, молимо контактирајте корисничку подршку",
    300: "Соба није пронађена",
    301: "Ова соба је близу",
    302: "Добро није пронађено",
    303: "Већ сте користили овај купон за точкове!",
    400: "Данашње ограничење поруџбине је пуно",
    401: "Ова наруџбина је већ завршена",
    402: "Не можете креирати наруџбу",
    403: "Недовољан баланс",
    404: "Данас нема шансе за окретање",
    405: "Ваша последња наруџбина још није завршена!",
    407: "Ваша наредба је одбијена",
    409: "Ова наредба је већ завршена!",
    500: "Системска грешка",
    600: "Ваше стање треба да буде између минималне и максималне цене",
    'LoginFirst':"Морате пријавити !",
    
  },
  fr: {
    100: "Erreur système",
    101: "Système introuvable",
    102: "Paramètre système erroné",
    103: "Validation de l'erreur système",
    104: "Le jeton système a expiré",
    105: "Charge utile du système trop importante",
    200: "Code de vérification incorrect",
    201: "Mot de passe utilisateur erroné",
    202: "L'utilisateur existe déjà",
    203: "Nom d'utilisateur invalide",
    204: "Code d'invitation invalide",
    205: "Ce compte est désactivé",
    206: "Utilisateur sans autorisation",
    207: "Numéro de téléphone invalide",
    208: "L'utilisateur n'a pas de solde",
    209: "Solde insuffisant",
    210: "Cette adresse de portefeuille existe déjà",
    211: "Réseau principal invalide",
    212: "E-mail invalide",
    213: "Nom d'utilisateur invalide",
    214: "L'utilisateur n'existe pas",
    215: "Ancien mot de passe invalide",
    216: "Vous avez déjà lié l'adresse de retrait !",
    217: "Vous n'avez pas l'autorisation de déposer, veuillez contacter le service client",
    218: "Vous n'êtes pas autorisé à vous rétracter, veuillez contacter le service client",
    300: "Pièce introuvable",
    301: "Cette salle est proche",
    302: "Bon introuvable",
    303: "Vous avez déjà utilisé ce bol de roue !",
    400: "La limite de commande aujourd'hui est pleine",
    401: "Cette commande est déjà terminée",
    402: "Vous ne pouvez pas créer de commande",
    403: "Solde insuffisant",
    404: "Aucune chance de tourner aujourd'hui",
    405: "Votre dernière commande n'est pas encore terminée !",
    407: "Votre commande a été rejetée",
    409: "Cette commande est déjà terminée !",
    500: "Erreur système",
    600: "Votre solde doit être compris entre le prix minimum et le prix maximum",
    'LoginFirst':"S'il vous plait Connectez-vous d'abord !",
  },
  pt: {
    100: "Erro do sistema",
    101: "Sistema não encontrado",
    102: "Parâmetro errado do sistema",
    103: "Validação de erro do sistema",
    104: "Token do sistema expirou",
    105: "Carga útil do sistema muito grande",
    200: "Código de verificação incorreto",
    201: "Senha errada do usuário",
    202: "Usuário já existe",
    203: "Nome de usuário inválido",
    204: "Código de convite inválido",
    205: "Esta conta está desativada",
    206: "Usuário sem permissão",
    207: "Número de telefone inválido",
    208: "Usuário não tem saldo",
    209: "Saldo Insuficiente",
    210: "Este endereço de carteira já existe",
    211: "Rede principal inválida",
    212: "E-mail inválido",
    213: "Nome de usuário inválido",
    214: "Usuário não existe",
    215: "Senha antiga inválida",
    216: "Você já vincula o endereço de retirada!",
    217: "Você não tem permissão para depositar, entre em contato com o atendimento ao cliente",
    218: "Você não tem permissão para retirar, entre em contato com o atendimento ao cliente",
    300: "Quarto não encontrado",
    301: "Este quarto é próximo",
    302: "Bom não encontrado",
    303: "Você já usou este cupão de roda!",
    400: "O limite de pedidos de hoje está cheio",
    401: "Este pedido já foi concluído",
    402: "Você não pode criar um pedido",
    403: "Equilíbrio insuficiente",
    404: "Sem chance de girar hoje",
    405: "Seu último pedido ainda não foi finalizado!",
    407: "Seu pedido foi rejeitado",
    409: "Este pedido já terminou!",
    500: "Erro do sistema",
    600: "Seu saldo deve estar entre o preço mínimo e o preço máximo",
    'LoginFirst':"Por favor, faça o login primeiro!",
  },
  de: {
    100: "Systemfehler",
    101: "System nicht gefunden",
    102: "System falscher Parameter",
    103: "Systemfehlervalidierung",
    104: "System-Token abgelaufen",
    105: "Systemnutzlast zu groß",
    200: "Falscher Bestätigungscode",
    201: "Benutzer falsches Passwort",
    202: "Benutzer existiert bereits",
    203: "Benutzername ungültig",
    204: "Ungültiger Einladungscode",
    205: "Dieses Konto ist deaktiviert",
    206: "Benutzer keine Berechtigung",
    207: "Ungültige Telefonnummer",
    208: "Benutzer hat kein Guthaben",
    209: "Unzureichendes Guthaben",
    210: "Diese Wallet-Adresse existiert bereits",
    211: "Ungültiges Hauptnetz",
    212: "Ungültige E-Mail",
    213: "Ungültiger Benutzername",
    214: "Benutzer existiert nicht",
    215: "Ungültiges altes Passwort",
    216: "Sie haben bereits eine Abhebungsadresse gebunden!",
    217: "Sie haben keine Einzahlungserlaubnis, bitte kontaktieren Sie den Kundendienst",
    218: "Sie haben keine Berechtigung zum Widerruf, bitte kontaktieren Sie den Kundendienst",
    300: "Raum nicht gefunden",
    301: "Dieser Raum ist geschlossen",
    302: "Gut nicht gefunden",
    303: "Du hast diesen Radbecher bereits benutzt!",
    400: "Heute ist das Bestelllimit voll",
    401: "Diese Bestellung ist bereits abgeschlossen",
    402: "Sie können keine Bestellung erstellen",
    403: "Unzureichendes Guthaben",
    404: "Heute keine Spin-Chance",
    405: "Ihre letzte Bestellung war noch nicht abgeschlossen!",
    407: "Ihre Bestellung wurde abgelehnt",
    409: "Dieser Auftrag ist bereits beendet!",
    500: "Systemfehler",
    600: "Ihr Guthaben sollte zwischen Mindestpreis und Höchstpreis liegen",
    'LoginFirst':"Bitte loggen Sie sich zuerst ein !",
  },
  nl: {
    100: "Systeemfout",
    101: "Systeem niet gevonden",
    102: "Systeem verkeerde parameter",
    103: "Systeemfoutvalidatie",
    104: "Systeemtoken verlopen",
    105: "Systeemlading te groot",
    200: "Onjuiste verificatiecode",
    201: "Gebruiker verkeerd wachtwoord",
    202: "Gebruiker bestaat al",
    203: "Gebruikersnaam ongeldig",
    204: "Ongeldige uitnodigingscode",
    205: "Dit account is uitgeschakeld",
    206: "Gebruiker geen toestemming",
    207: "Ongeldig telefoonnummer",
    208: "Gebruiker heeft geen saldo",
    209: "Onvoldoende saldo",
    210: "Dit portemonnee-adres bestaat al",
    211: "Ongeldig hoofdnet",
    212: "Ongeldige e-mail",
    213: "Ongeldige gebruikersnaam",
    214: "Gebruiker bestaat niet",
    215: "Ongeldig oud wachtwoord",
    216: "Je bindt adres al intrekken!",
    217: "U heeft geen toestemming om te storten, neem contact op met de klantenservice",
    218: "Je hebt geen toestemming om in te trekken, neem contact op met de klantenservice",
    300: "Kamer niet gevonden",
    301: "Deze kamer is dichtbij",
    302: "Goed niet gevonden",
    303: "Je hebt deze wielbeker al gebruikt!",
    400: "De bestellimiet van vandaag is vol",
    401: "Deze bestelling is al voltooid",
    402: "U kunt geen bestelling maken",
    403: "Onvoldoende saldo",
    404: "Geen spin-kans vandaag",
    405: "Je laatste bestelling is nog niet af!",
    407: "Uw bestelling is afgewezen",
    409: "Deze bestelling is al klaar!",
    500: "Systeemfout",
    600: "Uw balane moet tussen de minimumprijs en de maximumprijs liggen",
    'LoginFirst':"Log alstublieft eerst in !",
  },
  hr:{
    100: "Errore di u sistema",
    101: "Sistema micca truvatu",
    102: "Parametru di sistema sbagliatu",
    103: "Validazione di l'errore di u sistema",
    104: "Token di sistema scadutu",
    105: "Carica di sistema troppu grande",
    200: "Codice di verificazione sbagliatu",
    201: "User password sbagliata",
    202: "L'utilizatore esiste digià",
    203: "Username Invalid",
    204: "Codice d'invitu invalidu",
    205: "Stu contu hè disattivatu",
    206: "User senza permessu",
    207: "Numeru di telefunu invalidu",
    208: "L'utilizatore ùn hà micca equilibriu",
    209: "Balance insuffisante",
    210: "Questu indirizzu di portafogli esiste digià",
    211: "mainnet invalidu",
    212: "E-mail invalidu",
    213: "Nome d'utilizatore invalidu",
    214: "L'utilizatore ùn esiste micca",
    215: "Vecchia password invalida",
    216: "Avete digià vintu l'indirizzu di ritirata!",
    217: "Ùn avete micca permessu di deposità, per piacè cuntattate u serviziu di u cliente",
    218: "Ùn avete micca permessu di ritirà, per piacè cuntattate u serviziu di u cliente",
    300: "Camera micca trovu",
    301: "Questa stanza hè vicinu",
    302: "Bè micca trovu",
    303: "Avete digià utilizatu stu cuponu di rota!",
    400: "U limitu di ordini oghje hè pienu",
    401: "Questu ordine hè digià cumpletu",
    402: "Ùn pudete micca creà un ordine",
    403: "Balance insuffisante",
    404: "Nisuna chance di spin oghje",
    405: "U vostru ultimu ordine ùn hè ancu finitu!",
    407: "U vostru ordine hè statu rifiutatu",
    409: "Questu ordine hè digià finitu!",
    500: "Errore di sistema",
    600: "U vostru equilibriu deve esse trà u prezzu minimu è u prezzu massimu",
    'LoginFirst':"Per piacè accede prima!",
  },
  ca: {
    100: "Error del sistema",
    101: "No s'ha trobat el sistema",
    102: "El paràmetre del sistema és incorrecte",
    103: "Validació d'error del sistema",
    104: "El testimoni del sistema ha caducat",
    105: "La càrrega útil del sistema és massa gran",
    200: "Codi de verificació incorrecte",
    201: "Usuari contrasenya incorrecta",
    202: "L'usuari ja existeix",
    203: "El nom d'usuari no és vàlid",
    204: "Codi d'invitació no vàlid",
    205: "Aquest compte està desactivat",
    206: "L'usuari no té permís",
    207: "Número de telèfon no vàlid",
    208: "L'usuari no té saldo",
    209: "Saldo insuficient",
    210: "Aquesta adreça de cartera ja existeix",
    211: "Xarxa principal no vàlida",
    212: "Correu electrònic no vàlid",
    213: "Nom d'usuari no vàlid",
    214: "L'usuari no existeix",
    215: "Contrasenya antiga no vàlida",
    216: "Ja lliga l'adreça de retirada!",
    217: "No teniu permís per dipositar, poseu-vos en contacte amb el servei d'atenció al client",
    218: "No teniu permís per retirar-vos, poseu-vos en contacte amb el servei d'atenció al client",
    300: "No s'ha trobat l'habitació",
    301: "Aquesta habitació està a prop",
    302: "No s'ha trobat bé",
    303: "Ja has utilitzat aquest cupon de roda!",
    400: "El límit de comandes d'avui és ple",
    401: "Aquesta comanda ja s'ha completat",
    402: "No podeu crear una comanda",
    403: "Saldo insuficient",
    404: "No hi ha possibilitat de girar avui",
    405: "La teva última comanda encara no s'ha acabat!",
    407: "La teva comanda ha estat rebutjada",
    409: "Aquesta comanda ja s'ha acabat!",
    500: "Error del sistema",
    600: "El vostre saldo hauria d'entre el preu mínim i el preu màxim",
    'LoginFirst':"Si us plau, inicieu sessió primer!",
  },
  tr: {
    100: "Sistem hatası",
    101: "Sistem Bulunamadı",
    102: "Sistem yanlış parametresi",
    103: "Sistem Hatası Doğrulaması",
    104: "Sistem belirtecinin süresi doldu",
    105: "Sistem yükü çok büyük",
    200: "Yanlış doğrulama kodu",
    201: "Kullanıcı yanlış şifre",
    202: "Kullanıcı zaten var",
    203: "Kullanıcı Adı Geçersiz",
    204: "Geçersiz davet kodu",
    205: "Bu hesap devre dışı",
    206: "Kullanıcı izni yok",
    207: "Geçersiz Telefon numarası",
    208: "Kullanıcının bakiyesi yok",
    209: "Yetersiz Bakiye",
    210: "Bu cüzdan adresi zaten var",
    211: "Geçersiz ana ağ",
    212: "Geçersiz E-posta",
    213: "Geçersiz Kullanıcı Adı",
    214: "Kullanıcı mevcut değil",
    215: "Geçersiz eski şifre",
    216: "Çekim adresini zaten bağladın!",
    217: "Para yatırma izniniz yok, lütfen müşteri hizmetleri ile iletişime geçin",
    218: "Çekme izniniz yok, lütfen müşteri hizmetleri ile iletişime geçin",
    300: "Oda bulunamadı",
    301: "Bu Oda yakın",
    302: "İyi bulunamadı",
    303: "Bu tekerlek kupasını zaten kullandınız!",
    400: "Bugün sipariş limiti doldu",
    401: "Bu sipariş zaten tamamlandı",
    402: "Sipariş oluşturamazsınız",
    403: "Yetersiz bakiye",
    404: "Bugün spin şansı yok",
    405: "Son siparişiniz henüz bitmedi!",
    407: "Siparişiniz reddedildi",
    409: "Bu sipariş zaten bitti!",
    500: "Sistem Hatası",
    600: "Dengeniz minimum fiyat ile maksimum fiyat arasında olmalıdır",
    'LoginFirst':"Lütfen önce giriş yapınız !",
  },
  ru: {
    100: "Системная ошибка",
    101: "Система не найдена",
    102: "Системный неверный параметр",
    103: "Проверка системной ошибки",
    104: "Срок действия системного токена истек",
    105: "Полезная нагрузка системы слишком велика",
    200: "Неверный проверочный код",
    201: "Неверный пароль пользователя",
    202: "Пользователь уже существует",
    203: "Неверное имя пользователя",
    204: "Неверный код приглашения",
    205: "Эта учетная запись отключена",
    206: "У пользователя нет разрешения",
    207: "Неверный номер телефона",
    208: "У пользователя нет баланса",
    209: "Недостаточный баланс",
    210: "Этот адрес кошелька уже существует",
    211: "Неверная основная сеть",
    212: "Неверный адрес электронной почты",
    213: "Неверное имя пользователя",
    214: "Пользователь не существует",
    215: "Неверный старый пароль",
    216: "Вы уже привязали адрес вывода!",
    217: "У вас нет разрешения на депозит, обратитесь в службу поддержки",
    218: "У вас нет разрешения на снятие средств, обратитесь в службу поддержки",
    300: "Комната не найдена",
    301: "Эта комната близко",
    302: "Хорошо не найдено",
    303: "Вы уже использовали этот колпачок!",
    400: "Сегодня лимит заказов исчерпан",
    401: "Этот заказ уже выполнен",
    402: "Вы не можете создать заказ",
    403: "Недостаточный баланс",
    404: "Сегодня нет шансов на вращение",
    405: "Ваш последний заказ еще не выполнен!",
    407: "Ваш заказ отклонен",
    409: "Этот заказ уже закончен!",
    500: "Системная ошибка",
    600: "Ваш баланс должен быть между минимальной и максимальной ценой",
    'LoginFirst':"Пожалуйста, войдите сначала !",
  },
};
